In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\PRO\Desktop\Morocco Education Data Intelligence Platform\data\bronze\ds9_appui_social.csv")
df.head()

,id_beneficiaire,annee_scolaire,region,code_region,milieu,genre,cycle,type_aide,montant_aide_mad,organisme_financeur
0,AS600000,2020-2021,Casablanca-Settat,CAS,Rural,Féminin,Collégial,Cartable,173,MEN
1,AS600001,2018-2019,Tanger-Tétouan-Al Hoceïma,TAN,Rural,Masculin,Qualifiant,Internat,3614,MEN
2,AS600002,2016-2017,Béni Mellal-Khénifra,BMK,Rural,Féminin,Primaire,Cartable,170,MEN
3,AS600003,2023-2024,Souss-Massa,SOU,Rural,Masculin,Collégial,Cartable,171,MEN
4,AS600004,2023-2024,Rabat-Salé-Kénitra,RAB,Urbain,Féminin,Primaire,Uniforme,266,INDH

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_beneficiaire      6000 non-null   str
 1   annee_scolaire       6000 non-null   str
 2   region               6000 non-null   str
 3   code_region          6000 non-null   str
 4   milieu               6000 non-null   str
 5   genre                6000 non-null   str
 6   cycle                6000 non-null   str
 7   type_aide            6000 non-null   str
 8   montant_aide_mad     6000 non-null   int64
 9   organisme_financeur  6000 non-null   str
dtypes: int64(1), str(9)
memory usage: 468.9 KB

In [4]:
df.shape

(6000, 10)

In [6]:
df.columns

Index(['id_beneficiaire', 'annee_scolaire', 'region', 'code_region', 'milieu',
       'genre', 'cycle', 'type_aide', 'montant_aide_mad',
       'organisme_financeur'],
      dtype='str')

In [5]:
df.describe()

       montant_aide_mad
count       6000.000000
mean        1195.483500
std         1183.105791
min          106.000000
25%          173.000000
50%         1059.500000
75%         1816.000000
max         4493.000000

In [7]:
double=df.duplicated().sum()
double

np.int64(0)

In [8]:
# Sélection des colonnes numériques
numeric_df = df.select_dtypes(include="number")

# Calcul du skewness
skewness = numeric_df.skew()

print(skewness)

montant_aide_mad    0.941502
dtype: float64