In [2]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r"C:\Users\PRO\Desktop\Morocco Education Data Intelligence Platform\data\bronze\ds2_etablissements.csv")
df.head()

,id_etablissement,nom_etablissement,annee_scolaire,region,code_region,province,milieu,secteur,cycle,nb_classes,effectif_eleves,annee_creation,equipement_bibliotheque,equipement_laboratoire,equipement_salle_sport,acces_internet,cantine,latitude,longitude
0,ETB10000,École 472-TAN,2021-2022,Tanger-Tétouan-Al Hoceïma,TAN,Fahs-Anjra,Rural,Public,Primaire,15,274,1976,0,0,1,0,0,31.21237,-5.12716
1,ETB10001,École 215-FES,2022-2023,Fès-Meknès,FES,Taza,Urbain,Privé,Primaire,3,317,1999,1,0,1,1,1,29.07572,-8.95286
2,ETB10002,Collège 224-ORI,2018-2019,Oriental,ORI,Driouch,Urbain,Privé,Collégial,12,330,1981,1,1,0,1,1,28.02939,-7.39556
3,ETB10003,Lycée 351-LAA,2018-2019,Laâyoune-Sakia El Hamra,LAA,Laâyoune,Rural,Public,Qualifiant,17,324,1982,0,0,1,0,1,32.11913,-13.01069
4,ETB10004,OFPPT 241-MAR,2017-2018,Marrakech-Safi,MAR,Essaouira,Rural,Privé,Formation Professionnelle,27,346,2010,0,0,0,1,1,31.75383,-10.21850

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_etablissement         3000 non-null   str
 1   nom_etablissement        3000 non-null   str
 2   annee_scolaire           3000 non-null   str
 3   region                   3000 non-null   str
 4   code_region              3000 non-null   str
 5   province                 3000 non-null   str
 6   milieu                   3000 non-null   str
 7   secteur                  3000 non-null   str
 8   cycle                    3000 non-null   str
 9   nb_classes               3000 non-null   int64
 10  effectif_eleves          3000 non-null   int64
 11  annee_creation           3000 non-null   int64
 12  equipement_bibliotheque  3000 non-null   int64
 13  equipement_laboratoire   3000 non-null   int64
 14  equipement_salle_sport   3000 non-null   int64
 15  acces_internet           3000 non-null   int64
 16  cantine                  3000 non-null   int64
 17  latitude                 3000 non-null   float64
 18  longitude                3000 non-null   float64
dtypes: float64(2), int64(8), str(9)
memory usage: 445.4 KB

In [5]:
df.dtypes

id_etablissement               str
nom_etablissement              str
annee_scolaire                 str
region                         str
code_region                    str
province                       str
milieu                         str
secteur                        str
cycle                          str
nb_classes                   int64
effectif_eleves              int64
annee_creation               int64
equipement_bibliotheque      int64
equipement_laboratoire       int64
equipement_salle_sport       int64
acces_internet               int64
cantine                      int64
latitude                   float64
longitude                  float64
dtype: object

In [6]:
df.shape

(3000, 19)

In [7]:
df.columns

Index(['id_etablissement', 'nom_etablissement', 'annee_scolaire', 'region',
       'code_region', 'province', 'milieu', 'secteur', 'cycle', 'nb_classes',
       'effectif_eleves', 'annee_creation', 'equipement_bibliotheque',
       'equipement_laboratoire', 'equipement_salle_sport', 'acces_internet',
       'cantine', 'latitude', 'longitude'],
      dtype='str')

In [8]:
df.describe()

,nb_classes,effectif_eleves,annee_creation,equipement_bibliotheque,equipement_laboratoire,equipement_salle_sport,acces_internet,cantine,latitude,longitude
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,18.555333,410.020667,1990.468000,0.487000,0.393667,0.549333,0.620333,0.411000,31.862978,-7.113112
std,9.275143,429.669788,17.887658,0.499914,0.488644,0.497643,0.485385,0.492097,2.402130,3.554586
min,3.000000,23.000000,1960.000000,0.000000,0.000000,0.000000,0.000000,0.000000,27.704660,-13.199620
25%,10.000000,270.000000,1975.000000,0.000000,0.000000,0.000000,0.000000,0.000000,29.744010,-10.223133
50%,19.000000,345.000000,1990.000000,0.000000,0.000000,1.000000,1.000000,0.000000,31.874220,-7.169430
75%,27.000000,425.000000,2006.000000,1.000000,1.000000,1.000000,1.000000,1.000000,33.983387,-4.031410
max,34.000000,4311.000000,2021.000000,1.000000,1.000000,1.000000,1.000000,1.000000,35.899830,-1.009920

In [9]:
df.nunique()

id_etablissement           3000
nom_etablissement          2684
annee_scolaire                9
region                       12
code_region                  12
province                     71
milieu                        2
secteur                       2
cycle                         6
nb_classes                   32
effectif_eleves             650
annee_creation               62
equipement_bibliotheque       2
equipement_laboratoire        2
equipement_salle_sport        2
acces_internet                2
cantine                       2
latitude                   2996
longitude                  2992
dtype: int64

In [10]:
df.value_counts()

id_etablissement  nom_etablissement  annee_scolaire  region                     code_region  province       milieu  secteur  cycle                      nb_classes  effectif_eleves  annee_creation  equipement_bibliotheque  equipement_laboratoire  equipement_salle_sport  acces_internet  cantine  latitude  longitude
ETB10000          École 472-TAN      2021-2022       Tanger-Tétouan-Al Hoceïma  TAN          Fahs-Anjra     Rural   Public   Primaire                   15          274              1976            0                        0                       1                       0               0        31.21237  -5.12716     1
ETB10001          École 215-FES      2022-2023       Fès-Meknès                 FES          Taza           Urbain  Privé    Primaire                   3           317              1999            1                        0                       1                       1               1        29.07572  -8.95286     1
ETB10002          Collège 224-ORI    2018-2019       Oriental                   ORI          Driouch        Urbain  Privé    Collégial                  12          330              1981            1                        1                       0                       1               1        28.02939  -7.39556     1
ETB10003          Lycée 351-LAA      2018-2019       Laâyoune-Sakia El Hamra    LAA          Laâyoune       Rural   Public   Qualifiant                 17          324              1982            0                        0                       1                       0               1        32.11913  -13.01069    1
ETB10004          OFPPT 241-MAR      2017-2018       Marrakech-Safi             MAR          Essaouira      Rural   Privé    Formation Professionnelle  27          346              2010            0                        0                       0                       1               1        31.75383  -10.21850    1
                                                                                                                                                                                                                                                                                                                             ..
ETB12995          Collège 39-FES     2022-2023       Fès-Meknès                 FES          Moulay Yacoub  Rural   Public   Collégial                  22          357              1999            0                        0                       0                       1               0        29.96730  -2.14502     1
ETB12996          Collège 412-SOU    2022-2023       Souss-Massa                SOU          Tiznit         Rural   Public   Collégial                  15          582              1976            0                        0                       0                       0               0        33.43060  -11.91029    1
ETB12997          École 17-FES       2019-2020       Fès-Meknès                 FES          El Hajeb       Rural   Privé    Primaire                   34          359              1995            0                        0                       0                       1               0        34.58664  -10.66389    1
ETB12998          École 119-CAS      2016-2017       Casablanca-Settat          CAS          Sidi Bennour   Rural   Public   Primaire                   5           280              1972            1                        1                       0                       0               0        35.80226  -11.47597    1
ETB12999          École 399-FES      2019-2020       Fès-Meknès                 FES          Fès            Urbain  Privé    Primaire                   33          220              2020            1                        0                       0                       0               0        29.98886  -9.27636     1
Name: count, Length: 3000, dtype: int64

In [13]:
double=df.duplicated().sum()
double

np.int64(0)

In [12]:
# Sélection des colonnes numériques
numeric_df = df.select_dtypes(include="number")

# Calcul du skewness
skewness = numeric_df.skew()

print(skewness)

nb_classes                -0.019735
effectif_eleves            4.972930
annee_creation            -0.008850
equipement_bibliotheque    0.052044
equipement_laboratoire     0.435508
equipement_salle_sport    -0.198400
acces_internet            -0.496157
cantine                    0.361958
latitude                  -0.005419
longitude                 -0.002412
dtype: float64