In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv(r"C:\Users\PRO\Desktop\Morocco Education Data Intelligence Platform\data\bronze\ds5_budget_education.csv")
df.head()

,annee,region,code_region,poste_budgetaire,budget_alloue_mad,budget_execute_mad,taux_execution
0,2015,Casablanca-Settat,CAS,Salaires enseignants,40410362,31762545,0.786
1,2015,Casablanca-Settat,CAS,Infrastructures,8164972,6033914,0.739
2,2015,Casablanca-Settat,CAS,Équipements pédagogiques,3162985,2720167,0.860
3,2015,Casablanca-Settat,CAS,Appui social (cartables),2912729,2627282,0.902
4,2015,Casablanca-Settat,CAS,Restauration scolaire,2323001,2209174,0.951

In [3]:
df.shape

(972, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 972 entries, 0 to 971
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   annee               972 non-null    int64
 1   region              972 non-null    str
 2   code_region         972 non-null    str
 3   poste_budgetaire    972 non-null    str
 4   budget_alloue_mad   972 non-null    int64
 5   budget_execute_mad  972 non-null    int64
 6   taux_execution      972 non-null    float64
dtypes: float64(1), int64(3), str(3)
memory usage: 53.3 KB

In [5]:
df.columns

Index(['annee', 'region', 'code_region', 'poste_budgetaire',
       'budget_alloue_mad', 'budget_execute_mad', 'taux_execution'],
      dtype='str')

In [6]:
df.dtypes

annee                   int64
region                    str
code_region               str
poste_budgetaire          str
budget_alloue_mad       int64
budget_execute_mad      int64
taux_execution        float64
dtype: object

In [7]:
df.describe()

             annee  budget_alloue_mad  budget_execute_mad  taux_execution
count   972.000000       9.720000e+02        9.720000e+02       972.00000
mean   2019.000000       2.795919e+06        2.370981e+06         0.85342
std       2.583318       6.571144e+06        5.549441e+06         0.07841
min    2015.000000       1.101900e+04        8.512000e+03         0.72000
25%    2017.000000       2.577092e+05        2.123522e+05         0.78400
50%    2019.000000       7.001220e+05        5.975390e+05         0.85200
75%    2021.000000       1.614308e+06        1.370680e+06         0.92000
max    2023.000000       4.870218e+07        4.566761e+07         0.99000

In [8]:
double=df.duplicated().sum()
double

np.int64(0)

In [9]:
# Sélection des colonnes numériques
numeric_df = df.select_dtypes(include="number")

# Calcul du skewness
skewness = numeric_df.skew()

print(skewness)

annee                 0.000000
budget_alloue_mad     3.896682
budget_execute_mad    3.917100
taux_execution        0.054040
dtype: float64