In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"C:\Users\PRO\Desktop\Morocco Education Data Intelligence Platform\data\bronze\ds3_enseignants.csv")
df.head()

,id_enseignant,annee_scolaire,region,code_region,province,milieu,genre,cycle_enseigne,categorie,matiere,anciennete_annees,salaire_mensuel_mad,heures_semaine,formation_continue,jours_absence
0,ENS200000,2016-2017,Rabat-Salé-Kénitra,RAB,Sidi Kacem,Rural,Masculin,Primaire,Professeur certifié,Éducation islamique,25,5442,19,1,15
1,ENS200001,2017-2018,Casablanca-Settat,CAS,El Jadida,Urbain,Masculin,Qualifiant,Instituteur,Anglais,25,4387,19,1,0
2,ENS200002,2022-2023,Souss-Massa,SOU,Agadir-Ida-Ou-Tanane,Rural,Féminin,Primaire,Vacataire,Histoire-Géo,15,2953,25,1,0
3,ENS200003,2018-2019,Laâyoune-Sakia El Hamra,LAA,Laâyoune,Rural,Masculin,Primaire,Contractuel,Sciences,18,5305,22,0,0
4,ENS200004,2017-2018,Drâa-Tafilalet,DRA,Zagora,Rural,Féminin,Primaire,Contractuel,Mathématiques,24,5115,28,1,19

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_enseignant        8000 non-null   str
 1   annee_scolaire       8000 non-null   str
 2   region               8000 non-null   str
 3   code_region          8000 non-null   str
 4   province             8000 non-null   str
 5   milieu               8000 non-null   str
 6   genre                8000 non-null   str
 7   cycle_enseigne       8000 non-null   str
 8   categorie            8000 non-null   str
 9   matiere              8000 non-null   str
 10  anciennete_annees    8000 non-null   int64
 11  salaire_mensuel_mad  8000 non-null   int64
 12  heures_semaine       8000 non-null   int64
 13  formation_continue   8000 non-null   int64
 14  jours_absence        8000 non-null   int64
dtypes: int64(5), str(10)
memory usage: 937.6 KB

In [5]:
df.columns

Index(['id_enseignant', 'annee_scolaire', 'region', 'code_region', 'province',
       'milieu', 'genre', 'cycle_enseigne', 'categorie', 'matiere',
       'anciennete_annees', 'salaire_mensuel_mad', 'heures_semaine',
       'formation_continue', 'jours_absence'],
      dtype='str')

In [7]:
df.shape

(8000, 15)

In [8]:
df.dtypes

id_enseignant            str
annee_scolaire           str
region                   str
code_region              str
province                 str
milieu                   str
genre                    str
cycle_enseigne           str
categorie                str
matiere                  str
anciennete_annees      int64
salaire_mensuel_mad    int64
heures_semaine         int64
formation_continue     int64
jours_absence          int64
dtype: object

In [9]:
df.describe()

,anciennete_annees,salaire_mensuel_mad,heures_semaine,formation_continue,jours_absence
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,17.604750,5602.162250,24.567125,0.439875,8.808250
std,9.797935,1517.217273,4.036091,0.496403,8.198895
min,1.000000,826.000000,18.000000,0.000000,0.000000
25%,9.000000,4549.000000,21.000000,0.000000,0.000000
50%,18.000000,5482.000000,25.000000,0.000000,7.000000
75%,26.000000,6536.000000,28.000000,1.000000,16.000000
max,34.000000,10467.000000,31.000000,1.000000,24.000000

In [10]:
double=df.duplicated().sum()
double

np.int64(0)

In [11]:
is_null=df.isnull().mean()*100
is_null

id_enseignant          0.0
annee_scolaire         0.0
region                 0.0
code_region            0.0
province               0.0
milieu                 0.0
genre                  0.0
cycle_enseigne         0.0
categorie              0.0
matiere                0.0
anciennete_annees      0.0
salaire_mensuel_mad    0.0
heures_semaine         0.0
formation_continue     0.0
jours_absence          0.0
dtype: float64

In [12]:
# Sélection des colonnes numériques
numeric_df = df.select_dtypes(include="number")

# Calcul du skewness
skewness = numeric_df.skew()

print(skewness)

anciennete_annees     -0.016133
salaire_mensuel_mad    0.318817
heures_semaine        -0.007844
formation_continue     0.242303
jours_absence          0.388984
dtype: float64